-- ============================================================
--  AIOLIA – SCHÉMA FRONT / UTILISATEURS & BILLETTERIE
--  Génération : 2025-11-10
-- ============================================================
DROP DATABASE IF EXISTS aiolia_event;
DROP ROLE IF EXISTS aiolia_user;

CREATE ROLE aiolia_user WITH
    LOGIN
    PASSWORD 'aiolia2025'
    CREATEDB
    NOSUPERUSER
    NOCREATEROLE;

CREATE DATABASE aiolia_event
    WITH 
        OWNER = aiolia_user
        ENCODING = 'UTF8'
        LC_COLLATE = 'fr_FR.UTF-8'
        LC_CTYPE = 'fr_FR.UTF-8'
        TEMPLATE = template0;

\c aiolia_event;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS citext;

CREATE SCHEMA IF NOT EXISTS aiolia;
SET search_path TO aiolia, public;

-- ============================================================
-- Types énumérés
-- ============================================================
CREATE TYPE user_role_enum               AS ENUM ('admin', 'organizer', 'user');
CREATE TYPE auth_provider_enum           AS ENUM ('password', 'google', 'facebook');
CREATE TYPE event_status_enum            AS ENUM ('draft', 'published', 'cancelled', 'archived');
CREATE TYPE event_visibility_enum        AS ENUM ('public', 'private', 'unlisted');
CREATE TYPE ticket_status_enum           AS ENUM ('valid', 'used', 'cancelled', 'refunded', 'transferred');
CREATE TYPE ticket_transfer_status_enum  AS ENUM ('pending', 'accepted', 'declined', 'cancelled');
CREATE TYPE order_status_enum            AS ENUM ('pending', 'awaiting_payment', 'paid', 'cancelled', 'refunded', 'failed');
CREATE TYPE payment_status_enum          AS ENUM ('initiated', 'processing', 'paid', 'failed', 'refunded');
CREATE TYPE notification_channel_enum    AS ENUM ('email', 'sms', 'web_push');
CREATE TYPE notification_status_enum     AS ENUM ('pending', 'queued', 'sent', 'failed', 'read');
CREATE TYPE promotion_type_enum          AS ENUM ('percent', 'amount');
CREATE TYPE pricing_rule_type_enum       AS ENUM ('tier', 'time_window', 'promo');
CREATE TYPE wallet_transaction_type_enum AS ENUM ('credit', 'debit', 'points_credit', 'points_debit');
CREATE TYPE wallet_transaction_status_enum AS ENUM ('pending', 'completed', 'cancelled', 'failed');
CREATE TYPE referral_reward_type_enum    AS ENUM ('amount', 'percent', 'points');
CREATE TYPE invite_status_enum           AS ENUM ('pending', 'accepted', 'declined', 'expired');
CREATE TYPE subscription_status_enum     AS ENUM ('pending', 'active', 'past_due', 'suspended', 'cancelled', 'expired');
CREATE TYPE cart_status_enum             AS ENUM ('active', 'converted', 'abandoned', 'expired');
CREATE TYPE ticket_chance_status_enum    AS ENUM ('pending', 'won', 'lost', 'claimed');
CREATE TYPE organizer_type_enum          AS ENUM ('individual', 'company', 'non_profit', 'collective');

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'currency_code') THEN
        CREATE DOMAIN currency_code AS CHAR(3)
            CHECK (VALUE ~ '^[A-Z]{3}$');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'phone_e164') THEN
        CREATE DOMAIN phone_e164 AS VARCHAR(20)
            CHECK (VALUE ~ '^\+\d{6,18}$');
    END IF;
END
$$;

CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START WITH 100000;

-- ============================================================
-- Utilisateurs & Profils
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email CITEXT NOT NULL,
    login_identifier VARCHAR(255) NOT NULL,
    login_method VARCHAR(20) NOT NULL DEFAULT 'password',
    password_hash TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    phone TEXT,
    country_code CHAR(2),
    language_code VARCHAR(10) NOT NULL DEFAULT 'fr-FR',
    timezone TEXT NOT NULL DEFAULT 'Indian/Antananarivo',
    avatar_url TEXT,
    role user_role_enum NOT NULL DEFAULT 'user',
    status SMALLINT NOT NULL DEFAULT 0 CHECK (status IN (-1, 0, 1)),
    auth_provider VARCHAR(20) NOT NULL DEFAULT 'password',
    oauth_provider_id TEXT,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    two_factor_type VARCHAR(120),
    accepted_terms_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    CONSTRAINT uq_users_fullname UNIQUE (first_name, last_name),
    CONSTRAINT uq_users_login UNIQUE (login_identifier, login_method)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    phone phone_e164,
    country_code CHAR(2),
    language_code VARCHAR(10) NOT NULL DEFAULT 'fr-FR',
    timezone TEXT NOT NULL DEFAULT 'Indian/Antananarivo',
    avatar_url TEXT,
    dark_mode_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
    preferred_categories TEXT[],
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id BIGINT REFERENCES users(id),
    preference_key TEXT NOT NULL,
    preference_value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, preference_key)
);

CREATE TABLE IF NOT EXISTS user_search_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    keywords TEXT NOT NULL,
    filters JSONB,
    searched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_event_stats (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    events_attended INTEGER NOT NULL DEFAULT 0,
    upcoming_events INTEGER NOT NULL DEFAULT 0,
    total_spend NUMERIC(12,2) NOT NULL DEFAULT 0,
    favorite_categories TEXT[],
    last_event_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Journaux d'audit
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    scope VARCHAR(120) NOT NULL,
    action VARCHAR(120) NOT NULL,
    entity_type VARCHAR(120),
    entity_id BIGINT,
    changes JSONB,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_scope ON audit_logs(scope);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);

CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    currency currency_code NOT NULL DEFAULT 'MGA',
    balance NUMERIC(14,2) NOT NULL DEFAULT 0,
    points_balance INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES wallets(id),
    transaction_type wallet_transaction_type_enum NOT NULL,
    status wallet_transaction_status_enum NOT NULL DEFAULT 'pending',
    amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    points_delta INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    related_entity TEXT,
    related_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Organisations & Abonnements (front)
-- ============================================================
CREATE TABLE IF NOT EXISTS organizer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    display_name TEXT NOT NULL,
    legal_name TEXT,
    tax_number TEXT,
    support_email CITEXT,
    support_phone phone_e164,
    website_url TEXT,
    biography TEXT,
    organization_type organizer_type_enum NOT NULL DEFAULT 'individual',
    company_registration_number TEXT,
    company_size TEXT,
    verification_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (verification_status IN ('pending', 'verified', 'rejected')),
    onboarding_completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    billing_period TEXT NOT NULL
        CHECK (billing_period IN ('monthly', 'quarterly', 'yearly', 'lifetime')),
    period_count INTEGER NOT NULL DEFAULT 1 CHECK (period_count > 0),
    currency currency_code NOT NULL DEFAULT 'MGA',
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    vat_rate NUMERIC(5,2) NOT NULL DEFAULT 20,
    features JSONB,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS organizer_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NOT NULL REFERENCES organizer_profiles(id),
    plan_id BIGINT NOT NULL REFERENCES subscription_plans(id),
    status subscription_status_enum NOT NULL DEFAULT 'pending',
    starts_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    current_period_start TIMESTAMPTZ NOT NULL DEFAULT now(),
    current_period_end TIMESTAMPTZ,
    renewal_at TIMESTAMPTZ,
    cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
    cancelled_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Événements & Médias
-- ============================================================
CREATE TABLE IF NOT EXISTS event_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    label VARCHAR(255) NOT NULL,
    description TEXT,
    icon_name VARCHAR(120),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    primary_category_id BIGINT REFERENCES event_categories(id) ON DELETE SET NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255),
    summary TEXT,
    description TEXT,
    cover_image_url TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    visibility VARCHAR(20) NOT NULL DEFAULT 'public',
    capacity INTEGER,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Indian/Antananarivo',
    venue_id BIGINT,
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    sales_starts_at TIMESTAMPTZ,
    sales_ends_at TIMESTAMPTZ,
    age_restriction VARCHAR(120),
    language_code VARCHAR(10) NOT NULL DEFAULT 'fr-FR',
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_highlighted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS event_category_links (
    event_id BIGINT NOT NULL REFERENCES events(id),
    category_id BIGINT NOT NULL REFERENCES event_categories(id),
    PRIMARY KEY (event_id, category_id)
);

CREATE TABLE IF NOT EXISTS event_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS event_tag_links (
    event_id BIGINT NOT NULL REFERENCES events(id),
    tag_id BIGINT NOT NULL REFERENCES event_tags(id),
    PRIMARY KEY (event_id, tag_id)
);

CREATE TABLE IF NOT EXISTS event_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    title TEXT,
    description TEXT,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    capacity INTEGER,
    location_override TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS event_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    media_type VARCHAR(20) NOT NULL,
    url TEXT NOT NULL,
    alt_text TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Billetterie & Commandes
-- ============================================================
CREATE TABLE IF NOT EXISTS ticket_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    session_id BIGINT REFERENCES event_sessions(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    currency currency_code NOT NULL DEFAULT 'MGA',
    base_price NUMERIC(12,2) NOT NULL CHECK (base_price >= 0),
    service_fee NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (service_fee >= 0),
    vat_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    sales_start TIMESTAMPTZ,
    sales_end TIMESTAMPTZ,
    min_per_order INTEGER NOT NULL DEFAULT 1 CHECK (min_per_order > 0),
    max_per_order INTEGER CHECK (max_per_order IS NULL OR max_per_order >= min_per_order),
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_inventory (
    ticket_type_id BIGINT PRIMARY KEY REFERENCES ticket_types(id),
    total_quantity INTEGER NOT NULL CHECK (total_quantity >= 0),
    reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    sold_quantity INTEGER NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_type_id BIGINT NOT NULL REFERENCES ticket_types(id),
    changed_by BIGINT REFERENCES users(id),
    previous_price NUMERIC(12,2),
    new_price NUMERIC(12,2),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reason TEXT,
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status cart_status_enum NOT NULL DEFAULT 'active',
    session_token TEXT UNIQUE,
    currency currency_code NOT NULL DEFAULT 'MGA',
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id),
    ticket_type_id BIGINT NOT NULL REFERENCES ticket_types(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL,
    total_price NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (cart_id, ticket_type_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    cart_id BIGINT REFERENCES carts(id) ON DELETE SET NULL,
    status order_status_enum NOT NULL DEFAULT 'pending',
    total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    currency currency_code NOT NULL DEFAULT 'MGA',
    promotion_code TEXT,
    payment_due_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    ticket_type_id BIGINT NOT NULL REFERENCES ticket_types(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL,
    service_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
    vat_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    status_from order_status_enum,
    status_to order_status_enum NOT NULL,
    changed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    metadata JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT REFERENCES order_items(id) ON DELETE SET NULL,
    ticket_type_id BIGINT NOT NULL REFERENCES ticket_types(id),
    owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status ticket_status_enum NOT NULL DEFAULT 'valid',
    qr_code TEXT NOT NULL,
    qr_checksum TEXT,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS ticket_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets(id),
    from_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    to_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    to_email CITEXT,
    status ticket_transfer_status_enum NOT NULL DEFAULT 'pending',
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Wishlist, Gamification & Social
-- ============================================================
CREATE TABLE IF NOT EXISTS wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    title TEXT NOT NULL DEFAULT 'Favoris',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wishlist_items (
    wishlist_id BIGINT NOT NULL REFERENCES wishlists(id),
    event_id BIGINT NOT NULL REFERENCES events(id),
    added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (wishlist_id, event_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wishlists_default ON wishlists(user_id)
    WHERE is_default;

CREATE TABLE IF NOT EXISTS ticket_chance_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    event_id BIGINT REFERENCES events(id) ON DELETE SET NULL,
    prize_type promotion_type_enum NOT NULL,
    prize_value NUMERIC(12,2) NOT NULL DEFAULT 0,
    status ticket_chance_status_enum NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS user_connections (
    user_id BIGINT NOT NULL REFERENCES users(id),
    target_user_id BIGINT NOT NULL REFERENCES users(id),
    relation_type TEXT NOT NULL DEFAULT 'friend',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, target_user_id)
);

CREATE TABLE IF NOT EXISTS event_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    sender_user_id BIGINT NOT NULL REFERENCES users(id),
    recipient_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    recipient_email CITEXT,
    status invite_status_enum NOT NULL DEFAULT 'pending',
    token TEXT NOT NULL UNIQUE,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS referral_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_user_id BIGINT NOT NULL REFERENCES users(id),
    referred_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reward_type referral_reward_type_enum NOT NULL,
    reward_value NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    redeemed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS recommendation_cache (
    user_id BIGINT NOT NULL REFERENCES users(id),
    event_id BIGINT NOT NULL REFERENCES events(id),
    score NUMERIC(6,3) NOT NULL,
    reason TEXT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, event_id)
);

-- ============================================================
-- Notifications
-- ============================================================
CREATE TABLE IF NOT EXISTS notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    channel notification_channel_enum NOT NULL,
    subject TEXT,
    body TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    template_id BIGINT REFERENCES notification_templates(id) ON DELETE SET NULL,
    channel notification_channel_enum NOT NULL,
    status notification_status_enum NOT NULL DEFAULT 'pending',
    payload JSONB,
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id),
    status notification_status_enum NOT NULL,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Promotion Codes & Applications
-- ============================================================
CREATE TABLE IF NOT EXISTS promotion_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_profile_id BIGINT REFERENCES organizer_profiles(id) ON DELETE SET NULL,
    code TEXT NOT NULL UNIQUE,
    promotion_type promotion_type_enum NOT NULL,
    value NUMERIC(12,2) NOT NULL,
    max_usage_total INTEGER,
    max_usage_per_user INTEGER,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS promotion_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL REFERENCES promotion_codes(id),
    order_id BIGINT NOT NULL REFERENCES orders(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (promotion_id, order_id)
);

-- ============================================================
-- Pricing Rules
-- ============================================================
CREATE TABLE IF NOT EXISTS pricing_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_type_id BIGINT NOT NULL REFERENCES ticket_types(id),
    rule_type pricing_rule_type_enum NOT NULL,
    threshold_value NUMERIC(12,2),
    value NUMERIC(12,2),
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Indexes additionnels
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_events_dates ON events(starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_ticket_types_event ON ticket_types(event_id);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_wallet ON wallet_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_status ON notifications(user_id, status);

-- ------------------------------------------------------------
-- Paiements billets (factures, règlements, historique)
-- Permet de suivre les paiements liés aux commandes de billets
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ticket_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT NOT NULL UNIQUE DEFAULT LPAD(nextval('invoice_number_seq')::text, 8, '0'),
    order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    customer_id BIGINT NOT NULL REFERENCES users(id),
    currency currency_code NOT NULL DEFAULT 'MGA',
    subtotal_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'issued', 'paid', 'partially_paid', 'void', 'refunded', 'overdue')),
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES ticket_invoices(id),
    provider TEXT NOT NULL
        CHECK (provider IN ('orange', 'airtel', 'telma', 'bank_transfer')),
    provider_reference TEXT,
    status payment_status_enum NOT NULL DEFAULT 'initiated',
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    currency currency_code NOT NULL DEFAULT 'MGA',
    paid_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket_payment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES ticket_payments(id),
    status_from payment_status_enum,
    status_to payment_status_enum NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB
);

-- ------------------------------------------------------------
-- Paiements abonnements organisateurs 
-- (factures, règlements, historique)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subscription_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT NOT NULL UNIQUE DEFAULT LPAD(nextval('invoice_number_seq')::text, 8, '0'),
    subscription_id BIGINT NOT NULL REFERENCES organizer_subscriptions(id),
    customer_id BIGINT NOT NULL REFERENCES users(id),
    currency currency_code NOT NULL DEFAULT 'MGA',
    subtotal_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'issued', 'paid', 'partially_paid', 'void', 'refunded', 'overdue')),
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS subscription_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES subscription_invoices(id),
    provider TEXT NOT NULL
        CHECK (provider IN ('orange', 'airtel', 'telma', 'bank_transfer')),
    provider_reference TEXT,
    status payment_status_enum NOT NULL DEFAULT 'initiated',
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    currency currency_code NOT NULL DEFAULT 'MGA',
    paid_at TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS subscription_invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES subscription_invoices(id),
    plan_id BIGINT REFERENCES subscription_plans(id),
    description TEXT,
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS subscription_payment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES subscription_payments(id),
    status_from payment_status_enum,
    status_to payment_status_enum NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB
);

-- Index de support pour les recherches rapides
CREATE INDEX IF NOT EXISTS idx_ticket_invoices_status ON ticket_invoices(status);
CREATE INDEX IF NOT EXISTS idx_ticket_payments_invoice ON ticket_payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_subscription_invoices_status ON subscription_invoices(status);
CREATE INDEX IF NOT EXISTS idx_subscription_payments_invoice ON subscription_payments(invoice_id);


GRANT USAGE ON SCHEMA aiolia TO aiolia_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA aiolia TO aiolia_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA aiolia TO aiolia_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA aiolia
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aiolia_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA aiolia
    GRANT USAGE, SELECT ON SEQUENCES TO aiolia_user;

-- ------------------------------------------------------------
-- Récapitulatif
-- ------------------------------------------------------------
-- Total ENUM : 21
-- Total TABLES : 46
-- Total INDEXES : 11

