-- ============================================================
--  AIOLIA – SCHÉMA FRONT / UTILISATEURS & BILLETTERIE
--  Génération : 2025-11-10
--  Version : Toutes les tables et colonnes en français
-- ============================================================
DROP DATABASE IF EXISTS aiolia_event;
DROP ROLE IF EXISTS aiolia_user;

CREATE ROLE aiolia_user WITH
    LOGIN
    PASSWORD 'aiolia2025'
    CREATEDB
    NOSUPERUSER
    NOCREATEROLE;

CREATE DATABASE aiolia_event
    WITH 
        OWNER = aiolia_user
        ENCODING = 'UTF8'
        LC_COLLATE = 'fr_FR.UTF-8'
        LC_CTYPE = 'fr_FR.UTF-8'
        TEMPLATE = template0;

\c aiolia_event;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS citext;

CREATE SCHEMA IF NOT EXISTS aiolia;
SET search_path TO aiolia, public;

-- ============================================================
-- Types énumérés
-- ============================================================
CREATE TYPE user_role_enum               AS ENUM ('admin', 'organizer', 'user');
CREATE TYPE auth_provider_enum           AS ENUM ('password', 'google', 'facebook');
CREATE TYPE event_status_enum            AS ENUM ('draft', 'published', 'cancelled', 'archived');
CREATE TYPE event_visibility_enum        AS ENUM ('public', 'private', 'unlisted');
CREATE TYPE event_format_enum            AS ENUM ('in_person', 'online', 'hybrid');
CREATE TYPE ticket_status_enum           AS ENUM ('valid', 'used', 'cancelled', 'refunded', 'transferred');
CREATE TYPE ticket_transfer_status_enum  AS ENUM ('pending', 'accepted', 'declined', 'cancelled');
CREATE TYPE order_status_enum            AS ENUM ('pending', 'awaiting_payment', 'paid', 'cancelled', 'refunded', 'failed');
CREATE TYPE payment_status_enum          AS ENUM ('initiated', 'processing', 'paid', 'failed', 'refunded');
CREATE TYPE notification_channel_enum    AS ENUM ('email', 'sms', 'web_push');
CREATE TYPE notification_status_enum     AS ENUM ('pending', 'queued', 'sent', 'failed', 'read');
CREATE TYPE promotion_type_enum          AS ENUM ('percent', 'amount');
CREATE TYPE pricing_rule_type_enum       AS ENUM ('tier', 'time_window', 'promo');
CREATE TYPE wallet_transaction_type_enum AS ENUM ('credit', 'debit', 'points_credit', 'points_debit');
CREATE TYPE wallet_transaction_status_enum AS ENUM ('pending', 'completed', 'cancelled', 'failed');
CREATE TYPE referral_reward_type_enum      AS ENUM ('amount', 'percent', 'points');
CREATE TYPE invite_status_enum             AS ENUM ('pending', 'accepted', 'declined', 'expired');
CREATE TYPE subscription_status_enum       AS ENUM ('pending', 'active', 'paused');
CREATE TYPE cart_status_enum               AS ENUM ('active', 'converted', 'abandoned', 'expired');
CREATE TYPE ticket_chance_status_enum      AS ENUM ('pending', 'won', 'lost', 'claimed');
CREATE TYPE organizer_type_enum            AS ENUM ('individual', 'company', 'non_profit', 'collective');

-- Catégorie / type commercial du billet (VIP, Standard, Gratuit, etc.)
CREATE TYPE billet_categorie_enum AS ENUM (
    'tous',
    'standard',
    'vip',
    'gratuit',
    'promo',
    'early_bird',
    'backstage'
);

-- Segment d’âge ciblé par le billet
CREATE TYPE billet_segment_enum AS ENUM (
    'adulte',
    'enfant',
    'tous'
);

-- ============================================================
-- Configuration des segments de billets (pour gérer les âges)
-- ============================================================
CREATE TABLE IF NOT EXISTS configuration_segments_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom billet_segment_enum NOT NULL UNIQUE,
    age_min INTEGER,
    age_max INTEGER,
    pourcentage_prix NUMERIC(5,2) NOT NULL DEFAULT 0,
    est_actif BOOLEAN NOT NULL DEFAULT TRUE,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    supprime_le TIMESTAMPTZ
);

-- ============================================================
-- Configuration des catégories de billets (VIP, standard, etc.)
-- ============================================================
CREATE TABLE IF NOT EXISTS configuration_categories_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom billet_categorie_enum NOT NULL UNIQUE,
    description TEXT,
    pourcentage_prix NUMERIC(5,2) NOT NULL DEFAULT 0,
    est_actif BOOLEAN NOT NULL DEFAULT TRUE,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    supprime_le TIMESTAMPTZ
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'currency_code') THEN
        CREATE DOMAIN currency_code AS CHAR(3)
            CHECK (VALUE ~ '^[A-Z]{3}$');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'phone_e164') THEN
        CREATE DOMAIN phone_e164 AS VARCHAR(20)
            CHECK (VALUE ~ '^\+\d{6,18}$');
    END IF;
END
$$;

CREATE SEQUENCE IF NOT EXISTS sequence_numero_facture START WITH 100000;

-- ============================================================
-- Utilisateurs (table principale)
-- ============================================================
CREATE TABLE IF NOT EXISTS utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email CITEXT NOT NULL
        CHECK (email LIKE '%@%' AND email NOT LIKE '% %'),
    identifiant_connexion VARCHAR(255) NOT NULL,
    methode_connexion VARCHAR(20) NOT NULL DEFAULT 'password',
    hash_mot_de_passe TEXT NOT NULL,
    prenom TEXT NOT NULL,
    nom TEXT,
    telephone TEXT,
    code_pays CHAR(2),
    code_langue VARCHAR(10) NOT NULL DEFAULT 'fr-FR',
    fuseau_horaire TEXT NOT NULL DEFAULT 'Indian/Antananarivo',
    url_avatar TEXT,
    role user_role_enum NOT NULL DEFAULT 'user',
    statut SMALLINT NOT NULL DEFAULT 0 CHECK (statut IN (-1, 0, 1)),
    fournisseur_auth VARCHAR(20) NOT NULL DEFAULT 'password',
    id_fournisseur_oauth TEXT,
    email_verifie BOOLEAN NOT NULL DEFAULT FALSE,
    telephone_verifie BOOLEAN NOT NULL DEFAULT FALSE,
    type_double_authentification VARCHAR(120),
    termes_acceptes_le TIMESTAMPTZ,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    derniere_connexion_le TIMESTAMPTZ,
    CONSTRAINT uq_utilisateurs_nom_complet UNIQUE (prenom, nom),
    CONSTRAINT uq_utilisateurs_connexion UNIQUE (identifiant_connexion, methode_connexion)
);

CREATE INDEX IF NOT EXISTS idx_utilisateurs_email ON utilisateurs (email);

CREATE TABLE IF NOT EXISTS jetons_rafraichissement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id) ON DELETE CASCADE,
    hash_jeton TEXT NOT NULL,
    id_session UUID,
    user_agent TEXT,
    adresse_ip INET,
    metadonnees JSONB,
    emis_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    expire_le TIMESTAMPTZ NOT NULL,
    revoque_le TIMESTAMPTZ,
    remplace_par_jeton BIGINT REFERENCES jetons_rafraichissement(id),
    CONSTRAINT uq_jetons_rafraichissement_hash UNIQUE (hash_jeton),
    CHECK (expire_le > emis_le)
);

CREATE INDEX IF NOT EXISTS idx_jetons_rafraichissement_utilisateur ON jetons_rafraichissement(id_utilisateur);
CREATE INDEX IF NOT EXISTS idx_jetons_rafraichissement_actifs ON jetons_rafraichissement(id_utilisateur, expire_le) WHERE revoque_le IS NULL;

-- ============================================================
-- Profils Utilisateurs (role: user)
-- ============================================================
CREATE TABLE IF NOT EXISTS profils_utilisateurs (
    id_utilisateur BIGINT PRIMARY KEY REFERENCES utilisateurs(id),
    opt_in_marketing BOOLEAN NOT NULL DEFAULT FALSE,
    categories_preferees TEXT[],
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS preferences_utilisateurs (
    id_utilisateur BIGINT REFERENCES utilisateurs(id),
    cle_preference TEXT NOT NULL,
    valeur_preference JSONB NOT NULL,
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_utilisateur, cle_preference)
);

CREATE TABLE IF NOT EXISTS historique_recherches_utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    mots_cles TEXT NOT NULL,
    filtres JSONB,
    recherche_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS statistiques_evenements_utilisateurs (
    id_utilisateur BIGINT PRIMARY KEY REFERENCES utilisateurs(id),
    evenements_auxquels_a_participe INTEGER NOT NULL DEFAULT 0,
    evenements_a_venir INTEGER NOT NULL DEFAULT 0,
    depenses_totales NUMERIC(12,2) NOT NULL DEFAULT 0,
    categories_favorites TEXT[],
    dernier_evenement_le TIMESTAMPTZ,
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Profils Administrateurs (role: admin)
-- ============================================================
CREATE TABLE IF NOT EXISTS profils_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL UNIQUE REFERENCES utilisateurs(id),
    nom_affichage TEXT NOT NULL,
    nom_legal TEXT,
    numero_tva TEXT,
    email_support CITEXT,
    telephone_support phone_e164,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Journaux d'audit
-- ============================================================
CREATE TABLE IF NOT EXISTS journaux_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur_acteur BIGINT REFERENCES utilisateurs(id) ON DELETE SET NULL,
    portee VARCHAR(120) NOT NULL,
    action VARCHAR(120) NOT NULL,
    type_entite VARCHAR(120),
    id_entite BIGINT,
    modifications JSONB,
    adresse_ip INET,
    user_agent TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_journaux_audit_portee ON journaux_audit(portee);
CREATE INDEX IF NOT EXISTS idx_journaux_audit_cree_le ON journaux_audit(cree_le);
CREATE INDEX IF NOT EXISTS idx_journaux_audit_entite ON journaux_audit(type_entite, id_entite);

CREATE TABLE IF NOT EXISTS portefeuilles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL UNIQUE REFERENCES utilisateurs(id),
    devise currency_code NOT NULL DEFAULT 'MGA',
    solde NUMERIC(14,2) NOT NULL DEFAULT 0,
    solde_points INTEGER NOT NULL DEFAULT 0,
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transactions_portefeuilles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_portefeuille BIGINT NOT NULL REFERENCES portefeuilles(id),
    type_transaction wallet_transaction_type_enum NOT NULL,
    statut wallet_transaction_status_enum NOT NULL DEFAULT 'pending',
    montant NUMERIC(14,2) NOT NULL DEFAULT 0,
    variation_points INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    entite_liee TEXT,
    id_lie BIGINT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Profils Organisateurs (role: organizer)
-- ============================================================
CREATE TABLE IF NOT EXISTS profils_organisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL UNIQUE REFERENCES utilisateurs(id),
    nom_affichage TEXT NOT NULL,
    nom_legal TEXT,
    numero_tva TEXT,
    email_support CITEXT,
    telephone_support phone_e164,
    url_site_web TEXT,
    biographie TEXT,
    type_organisation organizer_type_enum NOT NULL DEFAULT 'individual',
    numero_immatriculation TEXT,
    taille_entreprise TEXT,
    statut_verification TEXT NOT NULL DEFAULT 'pending'
        CHECK (statut_verification IN ('pending', 'verified', 'rejected')),
    onboarding_termine_le TIMESTAMPTZ,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Abonnements Organisateurs
-- ============================================================
CREATE TABLE IF NOT EXISTS plans_abonnements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    nom TEXT NOT NULL,
    description TEXT,
    niveau TEXT NOT NULL DEFAULT 'basic'
        CHECK (niveau IN ('basic', 'pro', 'enterprise')),
    periode_facturation TEXT NOT NULL
        CHECK (periode_facturation IN ('monthly', 'quarterly', 'yearly')),
    nombre_periodes INTEGER NOT NULL DEFAULT 1 CHECK (nombre_periodes > 0),
    devise currency_code NOT NULL DEFAULT 'MGA',
    prix NUMERIC(12,2) NOT NULL CHECK (prix >= 0),
    taux_tva NUMERIC(5,2) NOT NULL DEFAULT 20,
    fonctionnalites JSONB,
    ordre_affichage INTEGER NOT NULL DEFAULT 0,
    est_actif BOOLEAN NOT NULL DEFAULT TRUE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_plans_abonnements_niveau UNIQUE (niveau, periode_facturation)
);

CREATE TABLE IF NOT EXISTS abonnements_organisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profil_organisateur BIGINT NOT NULL REFERENCES profils_organisateurs(id),
    id_plan BIGINT NOT NULL REFERENCES plans_abonnements(id),
    statut subscription_status_enum NOT NULL DEFAULT 'pending',
    mois_prepayes_restants INTEGER NOT NULL DEFAULT 0 CHECK (mois_prepayes_restants >= 0),
    commence_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    debut_periode_courante TIMESTAMPTZ NOT NULL DEFAULT now(),
    fin_periode_courante TIMESTAMPTZ,
    renouvellement_le TIMESTAMPTZ,
    annuler_a_la_fin_periode BOOLEAN NOT NULL DEFAULT FALSE,
    annule_le TIMESTAMPTZ,
    mis_en_pause_le TIMESTAMPTZ,
    repris_le TIMESTAMPTZ,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Lieux & Espaces
-- ============================================================
CREATE TABLE IF NOT EXISTS lieux (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profil_organisateur BIGINT REFERENCES profils_organisateurs(id) ON DELETE SET NULL,
    nom TEXT NOT NULL,
    slug VARCHAR(255) UNIQUE,
    description TEXT,
    ligne_adresse_1 TEXT,
    ligne_adresse_2 TEXT,
    ville TEXT,
    region TEXT,
    code_postal TEXT,
    code_pays CHAR(2) NOT NULL DEFAULT 'MG',
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    fuseau_horaire VARCHAR(64) NOT NULL DEFAULT 'Indian/Antananarivo',
    email_contact CITEXT,
    telephone_contact phone_e164,
    url_site_web TEXT,
    capacite INTEGER CHECK (capacite IS NULL OR capacite >= 0),
    equipements JSONB,
    notes_acces TEXT,
    est_actif BOOLEAN NOT NULL DEFAULT TRUE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS espaces_lieux (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lieu BIGINT NOT NULL REFERENCES lieux(id) ON DELETE CASCADE,
    nom TEXT NOT NULL,
    description TEXT,
    capacite INTEGER CHECK (capacite IS NULL OR capacite >= 0),
    plan JSONB,
    equipements JSONB,
    est_par_defaut BOOLEAN NOT NULL DEFAULT FALSE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id_lieu, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_espaces_lieux_par_defaut
    ON espaces_lieux(id_lieu)
    WHERE est_par_defaut;

-- ============================================================
-- Événements & Médias
-- ============================================================
CREATE TABLE IF NOT EXISTS categories_evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    libelle VARCHAR(255) NOT NULL,
    description TEXT,
    nom_icone VARCHAR(120),
    est_actif BOOLEAN NOT NULL DEFAULT TRUE,
    ordre_affichage INTEGER NOT NULL DEFAULT 0,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS types_evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(120) NOT NULL UNIQUE,
    libelle VARCHAR(255) NOT NULL,
    description TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profil_organisateur BIGINT REFERENCES profils_organisateurs(id) ON DELETE SET NULL,
    id_categorie_principale BIGINT REFERENCES categories_evenements(id) ON DELETE SET NULL,
    id_type_evenement BIGINT REFERENCES types_evenements(id) ON DELETE SET NULL,
    id_lieu BIGINT REFERENCES lieux(id) ON DELETE SET NULL,
    id_espace_principal BIGINT REFERENCES espaces_lieux(id) ON DELETE SET NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    titre VARCHAR(255) NOT NULL,
    sous_titre VARCHAR(255),
    resume TEXT,
    description TEXT,
    url_image_couverture TEXT,
    statut event_status_enum NOT NULL DEFAULT 'draft',
    visibilite event_visibility_enum NOT NULL DEFAULT 'public',
    format_evenement event_format_enum NOT NULL DEFAULT 'in_person',
    capacite INTEGER CHECK (capacite IS NULL OR capacite >= 0),
    fuseau_horaire VARCHAR(64) NOT NULL DEFAULT 'Indian/Antananarivo',
    localisation_override JSONB,
    url_live TEXT,
    plateforme_streaming TEXT,
    commence_le TIMESTAMPTZ NOT NULL,
    se_termine_le TIMESTAMPTZ NOT NULL,
    ventes_commencent_le TIMESTAMPTZ,
    ventes_se_terminent_le TIMESTAMPTZ,
    restriction_age VARCHAR(120),
    code_langue VARCHAR(10) NOT NULL DEFAULT 'fr-FR',
    est_en_vedette BOOLEAN NOT NULL DEFAULT FALSE,
    est_mis_en_avant BOOLEAN NOT NULL DEFAULT FALSE,
    url_youtube TEXT,
    nom_lieu_texte TEXT,
    adresse_complete TEXT,
    tarif_unique BOOLEAN NOT NULL DEFAULT FALSE,
    code_qr TEXT,
    checksum_qr TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (commence_le < se_termine_le),
    CHECK (
        ventes_commencent_le IS NULL
        OR ventes_se_terminent_le IS NULL
        OR ventes_commencent_le <= ventes_se_terminent_le
    ),

    CONSTRAINT fk_evenements_espace_principal
        FOREIGN KEY (id_lieu, id_espace_principal)
        REFERENCES espaces_lieux(id_lieu, id)
);


CREATE TABLE IF NOT EXISTS liens_categories_evenements (
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    id_categorie BIGINT NOT NULL REFERENCES categories_evenements(id),
    PRIMARY KEY (id_evenement, id_categorie)
);

CREATE TABLE IF NOT EXISTS tags_evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    libelle TEXT NOT NULL,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS liens_tags_evenements (
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    id_tag BIGINT NOT NULL REFERENCES tags_evenements(id),
    PRIMARY KEY (id_evenement, id_tag)
);

CREATE TABLE IF NOT EXISTS sessions_evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    id_espace_lieu BIGINT REFERENCES espaces_lieux(id) ON DELETE SET NULL,
    titre TEXT,
    description TEXT,
    commence_le TIMESTAMPTZ NOT NULL,
    se_termine_le TIMESTAMPTZ NOT NULL,
    capacite INTEGER,
    localisation_override JSONB,
    url_live TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (commence_le < se_termine_le),
    CHECK (capacite IS NULL OR capacite >= 0)
);

CREATE TABLE IF NOT EXISTS medias_evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    type_media VARCHAR(20) NOT NULL,
    url TEXT NOT NULL,
    texte_alternatif TEXT,
    ordre_affichage INTEGER NOT NULL DEFAULT 0,
    est_public BOOLEAN NOT NULL DEFAULT TRUE,
    format_affiche TEXT
        CHECK (format_affiche IS NULL OR format_affiche IN ('portrait', 'paysage')),
    est_affiche_principale BOOLEAN NOT NULL DEFAULT FALSE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Billetterie & Commandes
-- ============================================================
CREATE TABLE IF NOT EXISTS types_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    id_session BIGINT REFERENCES sessions_evenements(id) ON DELETE SET NULL,
    id_configuration_categorie BIGINT NOT NULL REFERENCES configuration_categories_billets(id),
    id_configuration_segment BIGINT NOT NULL REFERENCES configuration_segments_billets(id),
    nom TEXT NOT NULL,
    description TEXT,
    devise currency_code NOT NULL DEFAULT 'MGA',
    prix_de_base NUMERIC(12,2) NOT NULL CHECK (prix_de_base >= 0),
    frais_service NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (frais_service >= 0),
    taux_tva NUMERIC(5,2) NOT NULL DEFAULT 0,
    ventes_commencent_le TIMESTAMPTZ,
    ventes_se_terminent_le TIMESTAMPTZ,
    minimum_par_commande INTEGER NOT NULL DEFAULT 1 CHECK (minimum_par_commande > 0),
    maximum_par_commande INTEGER CHECK (maximum_par_commande IS NULL OR maximum_par_commande >= minimum_par_commande),
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventaire_billets (
    id_type_billet BIGINT PRIMARY KEY REFERENCES types_billets(id),
    quantite_totale INTEGER NOT NULL CHECK (quantite_totale >= 0),
    quantite_reservee INTEGER NOT NULL DEFAULT 0 CHECK (quantite_reservee >= 0),
    quantite_vendue INTEGER NOT NULL DEFAULT 0 CHECK (quantite_vendue >= 0),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS historique_prix_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type_billet BIGINT NOT NULL REFERENCES types_billets(id),
    modifie_par BIGINT REFERENCES utilisateurs(id),
    prix_precedent NUMERIC(12,2),
    nouveau_prix NUMERIC(12,2),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    raison TEXT,
    metadonnees JSONB
);

CREATE TABLE IF NOT EXISTS paniers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT REFERENCES utilisateurs(id) ON DELETE SET NULL,
    statut cart_status_enum NOT NULL DEFAULT 'active',
    jeton_session TEXT UNIQUE,
    devise currency_code NOT NULL DEFAULT 'MGA',
    montant_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    expire_le TIMESTAMPTZ,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS elements_paniers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_panier BIGINT NOT NULL REFERENCES paniers(id),
    id_type_billet BIGINT NOT NULL REFERENCES types_billets(id),
    quantite INTEGER NOT NULL CHECK (quantite > 0),
    prix_unitaire NUMERIC(12,2) NOT NULL,
    prix_total NUMERIC(12,2) NOT NULL,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id_panier, id_type_billet)
);

CREATE TABLE IF NOT EXISTS commandes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    id_panier BIGINT REFERENCES paniers(id) ON DELETE SET NULL,
    statut order_status_enum NOT NULL DEFAULT 'pending',
    montant_total NUMERIC(12,2) NOT NULL CHECK (montant_total >= 0),
    montant_remise NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (montant_remise >= 0),
    devise currency_code NOT NULL DEFAULT 'MGA',
    code_promotion TEXT,
    paiement_due_le TIMESTAMPTZ,
    notes TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS elements_commandes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_commande BIGINT NOT NULL REFERENCES commandes(id),
    id_type_billet BIGINT NOT NULL REFERENCES types_billets(id),
    quantite INTEGER NOT NULL CHECK (quantite > 0),
    prix_unitaire NUMERIC(12,2) NOT NULL,
    frais_service NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_tva NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_total NUMERIC(12,2) NOT NULL,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS historique_statuts_commandes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_commande BIGINT NOT NULL REFERENCES commandes(id),
    statut_de order_status_enum,
    statut_vers order_status_enum NOT NULL,
    modifie_par BIGINT REFERENCES utilisateurs(id) ON DELETE SET NULL,
    metadonnees JSONB,
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_element_commande BIGINT REFERENCES elements_commandes(id) ON DELETE SET NULL,
    id_type_billet BIGINT NOT NULL REFERENCES types_billets(id),
    id_utilisateur_proprietaire BIGINT REFERENCES utilisateurs(id) ON DELETE SET NULL,
    statut ticket_status_enum NOT NULL DEFAULT 'valid',
    code_qr TEXT NOT NULL,
    checksum_qr TEXT,
    emis_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadonnees JSONB
);

CREATE TABLE IF NOT EXISTS transferts_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_billet BIGINT NOT NULL REFERENCES billets(id),
    id_utilisateur_de BIGINT REFERENCES utilisateurs(id) ON DELETE SET NULL,
    id_utilisateur_vers BIGINT REFERENCES utilisateurs(id) ON DELETE SET NULL,
    email_vers CITEXT,
    statut ticket_transfer_status_enum NOT NULL DEFAULT 'pending',
    jeton TEXT NOT NULL UNIQUE,
    expire_le TIMESTAMPTZ,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Wishlist, Gamification & Social
-- ============================================================
CREATE TABLE IF NOT EXISTS listes_souhaits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    titre TEXT NOT NULL DEFAULT 'Favoris',
    est_par_defaut BOOLEAN NOT NULL DEFAULT FALSE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS elements_listes_souhaits (
    id_liste_souhaits BIGINT NOT NULL REFERENCES listes_souhaits(id),
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    ajoute_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_liste_souhaits, id_evenement)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_listes_souhaits_par_defaut ON listes_souhaits(id_utilisateur)
    WHERE est_par_defaut;

CREATE TABLE IF NOT EXISTS participations_loteries_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    id_evenement BIGINT REFERENCES evenements(id) ON DELETE SET NULL,
    type_lot promotion_type_enum NOT NULL,
    valeur_lot NUMERIC(12,2) NOT NULL DEFAULT 0,
    statut ticket_chance_status_enum NOT NULL DEFAULT 'pending',
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    reclame_le TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS connexions_utilisateurs (
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    id_utilisateur_cible BIGINT NOT NULL REFERENCES utilisateurs(id),
    type_relation TEXT NOT NULL DEFAULT 'friend',
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_utilisateur, id_utilisateur_cible)
);

CREATE TABLE IF NOT EXISTS invitations_evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    id_utilisateur_expediteur BIGINT NOT NULL REFERENCES utilisateurs(id),
    id_utilisateur_destinataire BIGINT REFERENCES utilisateurs(id) ON DELETE SET NULL,
    email_destinataire CITEXT,
    statut invite_status_enum NOT NULL DEFAULT 'pending',
    jeton TEXT NOT NULL UNIQUE,
    envoye_le TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS cache_recommandations (
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    id_evenement BIGINT NOT NULL REFERENCES evenements(id),
    score NUMERIC(6,3) NOT NULL,
    raison TEXT,
    genere_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_utilisateur, id_evenement)
);

-- ============================================================
-- Notifications
-- ============================================================
CREATE TABLE IF NOT EXISTS modeles_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    canal notification_channel_enum NOT NULL,
    sujet TEXT,
    corps TEXT NOT NULL,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    id_modele BIGINT REFERENCES modeles_notifications(id) ON DELETE SET NULL,
    canal notification_channel_enum NOT NULL,
    statut notification_status_enum NOT NULL DEFAULT 'pending',
    charge_utile JSONB,
    programme_le TIMESTAMPTZ,
    envoye_le TIMESTAMPTZ,
    lu_le TIMESTAMPTZ,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS historique_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_notification BIGINT NOT NULL REFERENCES notifications(id),
    statut notification_status_enum NOT NULL,
    message TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Promotion Codes & Applications
-- ============================================================
CREATE TABLE IF NOT EXISTS codes_promotionnels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profil_organisateur BIGINT REFERENCES profils_organisateurs(id) ON DELETE SET NULL,
    code TEXT NOT NULL UNIQUE,
    type_promotion promotion_type_enum NOT NULL,
    valeur NUMERIC(12,2) NOT NULL,
    utilisation_maximale_totale INTEGER,
    utilisation_maximale_par_utilisateur INTEGER,
    commence_le TIMESTAMPTZ,
    se_termine_le TIMESTAMPTZ,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS applications_promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_promotion BIGINT NOT NULL REFERENCES codes_promotionnels(id),
    id_commande BIGINT NOT NULL REFERENCES commandes(id),
    id_utilisateur BIGINT NOT NULL REFERENCES utilisateurs(id),
    montant_remise NUMERIC(12,2) NOT NULL DEFAULT 0,
    applique_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id_promotion, id_commande)
);

-- ============================================================
-- Pricing Rules
-- ============================================================
CREATE TABLE IF NOT EXISTS regles_tarification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type_billet BIGINT NOT NULL REFERENCES types_billets(id),
    type_regle pricing_rule_type_enum NOT NULL,
    valeur_seuil NUMERIC(12,2),
    valeur NUMERIC(12,2),
    commence_le TIMESTAMPTZ,
    se_termine_le TIMESTAMPTZ,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Modes de paiement acceptés par événement
-- ============================================================
CREATE TABLE IF NOT EXISTS modes_paiement_evenements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evenement BIGINT NOT NULL REFERENCES evenements(id) ON DELETE CASCADE,
    mode_paiement TEXT NOT NULL
        CHECK (mode_paiement IN ('espace', 'mvola', 'orange', 'airtel', 'telma', 'mastercard', 'visa', 'bank_transfer')),
    est_actif BOOLEAN NOT NULL DEFAULT TRUE,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id_evenement, mode_paiement)
);

-- ============================================================
-- Langues acceptées par événement
-- ============================================================
CREATE TABLE IF NOT EXISTS langues_evenements (
    id_evenement BIGINT NOT NULL REFERENCES evenements(id) ON DELETE CASCADE,
    code_langue VARCHAR(10) NOT NULL
        CHECK (code_langue IN ('mg', 'fr', 'en')),
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_evenement, code_langue)
);

-- ============================================================
-- Accessibilité des événements
-- ============================================================
CREATE TABLE IF NOT EXISTS accessibilite_evenements (
    id_evenement BIGINT NOT NULL REFERENCES evenements(id) ON DELETE CASCADE,
    type_accessibilite TEXT NOT NULL
        CHECK (type_accessibilite IN ('wheelchair', 'hearing', 'visual', 'mobility', 'cognitive', 'other')),
    description TEXT,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id_evenement, type_accessibilite)
);

-- ============================================================
-- Indexes additionnels
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_evenements_dates ON evenements(commence_le, se_termine_le);
CREATE INDEX IF NOT EXISTS idx_evenements_statut_visibilite ON evenements(statut, visibilite);
CREATE INDEX IF NOT EXISTS idx_evenements_organisateur ON evenements(id_profil_organisateur, commence_le);
CREATE INDEX IF NOT EXISTS idx_evenements_lieu ON evenements(id_lieu, id_espace_principal);
CREATE INDEX IF NOT EXISTS idx_lieux_ville ON lieux(ville, code_pays);
CREATE INDEX IF NOT EXISTS idx_espaces_lieux_lieu ON espaces_lieux(id_lieu);
CREATE INDEX IF NOT EXISTS idx_types_billets_evenement ON types_billets(id_evenement);
CREATE INDEX IF NOT EXISTS idx_commandes_utilisateur ON commandes(id_utilisateur);
CREATE INDEX IF NOT EXISTS idx_transactions_portefeuilles_portefeuille ON transactions_portefeuilles(id_portefeuille);
CREATE INDEX IF NOT EXISTS idx_notifications_utilisateur_statut ON notifications(id_utilisateur, statut);
CREATE INDEX IF NOT EXISTS idx_modes_paiement_evenements_evenement ON modes_paiement_evenements(id_evenement);
CREATE INDEX IF NOT EXISTS idx_langues_evenements_evenement ON langues_evenements(id_evenement);
CREATE INDEX IF NOT EXISTS idx_accessibilite_evenements_evenement ON accessibilite_evenements(id_evenement);

-- ------------------------------------------------------------
-- Paiements billets (factures, règlements, historique)
-- Permet de suivre les paiements liés aux commandes de billets
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS factures_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_facture TEXT NOT NULL UNIQUE DEFAULT LPAD(nextval('sequence_numero_facture')::text, 8, '0'),
    id_commande BIGINT REFERENCES commandes(id) ON DELETE SET NULL,
    id_client BIGINT NOT NULL REFERENCES utilisateurs(id),
    devise currency_code NOT NULL DEFAULT 'MGA',
    montant_sous_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_tva NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_ht DECIMAL(10,2) NOT NULL DEFAULT 0,
    montant_tva_detail DECIMAL(10,2) NOT NULL DEFAULT 0,
    montant_ttc DECIMAL(10,2) NOT NULL DEFAULT 0,
    -- Mode de paiement utilisé (espace, mvola, orange, airtel, telma, mastercard, visa, bank_transfer)
    methode_paiement TEXT
        CHECK (methode_paiement IS NULL OR methode_paiement IN ('espace', 'mvola', 'orange', 'airtel', 'telma', 'mastercard', 'visa', 'bank_transfer')),
    statut TEXT NOT NULL DEFAULT 'draft'
        CHECK (statut IN ('draft', 'issued', 'paid', 'partially_paid', 'void', 'refunded', 'overdue')),
    emise_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    echeance_le TIMESTAMPTZ,
    payee_le TIMESTAMPTZ,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paiements_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_facture BIGINT REFERENCES factures_billets(id),
    fournisseur TEXT NOT NULL
        CHECK (fournisseur IN ('espace', 'mvola', 'orange', 'airtel', 'telma', 'mastercard', 'visa', 'bank_transfer')),
    reference_fournisseur TEXT,
    statut payment_status_enum NOT NULL DEFAULT 'initiated',
    montant NUMERIC(12,2) NOT NULL CHECK (montant >= 0),
    devise currency_code NOT NULL DEFAULT 'MGA',
    paye_le TIMESTAMPTZ,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS historique_paiements_billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paiement BIGINT NOT NULL REFERENCES paiements_billets(id),
    statut_de payment_status_enum,
    statut_vers payment_status_enum NOT NULL,
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadonnees JSONB
);

-- ------------------------------------------------------------
-- Paiements abonnements organisateurs 
-- (factures, règlements, historique)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS factures_abonnements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_facture TEXT NOT NULL UNIQUE DEFAULT LPAD(nextval('sequence_numero_facture')::text, 8, '0'),
    id_abonnement BIGINT NOT NULL REFERENCES abonnements_organisateurs(id),
    id_client BIGINT NOT NULL REFERENCES utilisateurs(id),
    devise currency_code NOT NULL DEFAULT 'MGA',
    montant_sous_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_tva NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    montant_ht DECIMAL(10,2) NOT NULL DEFAULT 0,
    montant_tva_detail DECIMAL(10,2) NOT NULL DEFAULT 0,
    montant_ttc DECIMAL(10,2) NOT NULL DEFAULT 0,
    mois_facturation DATE NOT NULL,
    est_mois_pause BOOLEAN NOT NULL DEFAULT FALSE,
    est_prepayee BOOLEAN NOT NULL DEFAULT FALSE,
    methode_paiement TEXT
        CHECK (methode_paiement IS NULL OR methode_paiement IN ('espace', 'mvola', 'orange', 'airtel', 'telma', 'mastercard', 'visa', 'bank_transfer')),
    statut TEXT NOT NULL DEFAULT 'draft'
        CHECK (statut IN ('draft', 'issued', 'paid', 'pending', 'suspendue', 'partially_paid', 'void', 'refunded', 'overdue')),
    emise_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    echeance_le TIMESTAMPTZ,
    payee_le TIMESTAMPTZ,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paiements_abonnements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_facture BIGINT REFERENCES factures_abonnements(id),
    fournisseur TEXT NOT NULL
        CHECK (fournisseur IN ('espace', 'mvola', 'orange', 'airtel', 'telma', 'mastercard', 'visa', 'bank_transfer')),
    reference_fournisseur TEXT,
    statut payment_status_enum NOT NULL DEFAULT 'initiated',
    montant NUMERIC(12,2) NOT NULL CHECK (montant >= 0),
    devise currency_code NOT NULL DEFAULT 'MGA',
    paye_le TIMESTAMPTZ,
    metadonnees JSONB,
    cree_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS elements_factures_abonnements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_facture BIGINT NOT NULL REFERENCES factures_abonnements(id),
    id_plan BIGINT REFERENCES plans_abonnements(id),
    description TEXT,
    quantite INTEGER NOT NULL DEFAULT 1 CHECK (quantite > 0),
    prix_unitaire NUMERIC(12,2) NOT NULL CHECK (prix_unitaire >= 0),
    montant_total NUMERIC(12,2) NOT NULL CHECK (montant_total >= 0),
    metadonnees JSONB
);

CREATE TABLE IF NOT EXISTS historique_paiements_abonnements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paiement BIGINT NOT NULL REFERENCES paiements_abonnements(id),
    statut_de payment_status_enum,
    statut_vers payment_status_enum NOT NULL,
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadonnees JSONB
);

-- Index de support pour les recherches rapides
CREATE INDEX IF NOT EXISTS idx_factures_billets_statut ON factures_billets(statut);
CREATE INDEX IF NOT EXISTS idx_paiements_billets_facture ON paiements_billets(id_facture);
CREATE INDEX IF NOT EXISTS idx_factures_abonnements_statut ON factures_abonnements(statut);
CREATE INDEX IF NOT EXISTS idx_factures_abonnements_mois_facturation ON factures_abonnements(id_abonnement, mois_facturation);
CREATE INDEX IF NOT EXISTS idx_factures_abonnements_abonnement ON factures_abonnements(id_abonnement, statut);
CREATE INDEX IF NOT EXISTS idx_paiements_abonnements_facture ON paiements_abonnements(id_facture);
CREATE INDEX IF NOT EXISTS idx_abonnements_organisateurs_actifs ON abonnements_organisateurs(id_profil_organisateur, statut) WHERE statut IN ('active', 'paused');


GRANT USAGE ON SCHEMA aiolia TO aiolia_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA aiolia TO aiolia_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA aiolia TO aiolia_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA aiolia
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aiolia_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA aiolia
    GRANT USAGE, SELECT ON SEQUENCES TO aiolia_user;
