-- ============================================================
-- MISE À JOUR DU SCHÉMA POUR TICKET CHANCE
-- À exécuter avec un utilisateur admin (postgres)
-- ============================================================

-- Donner la propriété des tables à aiolia_user si nécessaire
-- ALTER TABLE aiolia.ticket_chance_entries OWNER TO aiolia_user;

-- Ajouter les nouvelles colonnes à ticket_chance_entries
ALTER TABLE aiolia.ticket_chance_entries 
ADD COLUMN IF NOT EXISTS play_type VARCHAR(20) DEFAULT 'free';

ALTER TABLE aiolia.ticket_chance_entries 
ADD COLUMN IF NOT EXISTS order_id BIGINT REFERENCES aiolia.orders(id) ON DELETE SET NULL;

ALTER TABLE aiolia.ticket_chance_entries 
ADD COLUMN IF NOT EXISTS prize_code VARCHAR(50);

ALTER TABLE aiolia.ticket_chance_entries 
ADD COLUMN IF NOT EXISTS promo_code VARCHAR(50);

ALTER TABLE aiolia.ticket_chance_entries 
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;

-- Créer la table promo_codes si elle n'existe pas
CREATE TABLE IF NOT EXISTS aiolia.promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_profile_id BIGINT REFERENCES aiolia.organizer_profiles(id) ON DELETE SET NULL,
    code TEXT NOT NULL UNIQUE,
    promotion_type VARCHAR(20) NOT NULL DEFAULT 'percent',
    value NUMERIC(12,2) NOT NULL,
    max_usage_total INTEGER,
    max_usage_per_user INTEGER DEFAULT 1,
    valid_from TIMESTAMPTZ DEFAULT NOW(),
    valid_until TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    ticket_chance_entry_id BIGINT REFERENCES aiolia.ticket_chance_entries(id) ON DELETE SET NULL,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Index pour les performances
CREATE INDEX IF NOT EXISTS idx_ticket_chance_entries_user_date 
    ON aiolia.ticket_chance_entries(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ticket_chance_entries_play_type 
    ON aiolia.ticket_chance_entries(user_id, play_type);

CREATE INDEX IF NOT EXISTS idx_promo_codes_code 
    ON aiolia.promo_codes(code);

CREATE INDEX IF NOT EXISTS idx_promo_codes_ticket_chance 
    ON aiolia.promo_codes(ticket_chance_entry_id) WHERE ticket_chance_entry_id IS NOT NULL;

-- Donner les permissions à aiolia_user
GRANT ALL PRIVILEGES ON aiolia.ticket_chance_entries TO aiolia_user;
GRANT ALL PRIVILEGES ON aiolia.promo_codes TO aiolia_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA aiolia TO aiolia_user;

-- Vérification
SELECT 'ticket_chance_entries columns:' as info;
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'aiolia' AND table_name = 'ticket_chance_entries'
ORDER BY ordinal_position;

SELECT 'promo_codes columns:' as info;
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'aiolia' AND table_name = 'promo_codes'
ORDER BY ordinal_position;

