-- ============================================================
-- TICKET CHANCE - STRUCTURE DES CADEAUX
-- ============================================================

-- Type enum pour les catégories de prix
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'prize_category_enum') THEN
        CREATE TYPE prize_category_enum AS ENUM (
            'discount',        -- Réductions (% ou montant fixe)
            'free_ticket',     -- Billet gratuit
            'upgrade',         -- Upgrade de catégorie
            'extra_play'       -- Tirage supplémentaire
        );
    END IF;
END
$$;

-- Table des prix disponibles
CREATE TABLE IF NOT EXISTS aiolia.ticket_chance_prizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Identification
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    
    -- Catégorie et valeur
    category prize_category_enum NOT NULL,
    value_type VARCHAR(20) NOT NULL DEFAULT 'fixed', -- 'fixed', 'percent', 'quantity'
    value NUMERIC(12,2) NOT NULL,
    
    -- Affichage sur la roue
    display_label VARCHAR(50) NOT NULL,
    color VARCHAR(7) NOT NULL DEFAULT '#4A90E2', -- Couleur hex
    icon VARCHAR(50) DEFAULT 'fa-gift',
    
    -- Probabilité et limites
    probability NUMERIC(5,4) NOT NULL DEFAULT 0.1000, -- 10% par défaut
    max_wins_per_day INTEGER,           -- Limite par jour (NULL = illimité)
    max_wins_per_user INTEGER,          -- Limite par utilisateur (NULL = illimité)
    
    -- Validité du prix gagné
    validity_days INTEGER DEFAULT 30,   -- Durée de validité après gain
    
    -- Conditions d'application
    min_order_amount NUMERIC(12,2),     -- Montant minimum pour utiliser
    applicable_categories TEXT[],        -- Catégories d'événements applicables
    applicable_event_ids BIGINT[],       -- Événements spécifiques applicables
    
    -- État
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    
    -- Métadonnées
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index pour les recherches
CREATE INDEX IF NOT EXISTS idx_ticket_chance_prizes_active 
    ON aiolia.ticket_chance_prizes(is_active, display_order);

-- ============================================================
-- DONNÉES INITIALES - CADEAUX PAR DÉFAUT
-- ============================================================

INSERT INTO aiolia.ticket_chance_prizes (
    code, name, description, category, value_type, value,
    display_label, color, icon, probability, validity_days, display_order
) VALUES
    -- Réductions en pourcentage
    (
        'DISCOUNT_50',
        'Méga Réduction -50%',
        'Réduction exceptionnelle de 50% sur votre prochain achat de billet.',
        'discount',
        'percent',
        50.00,
        '-50%',
        '#FF4757',
        'fa-fire',
        0.03,  -- 3% de chance (rare)
        14,
        1
    ),
    (
        'DISCOUNT_20',
        'Réduction -20%',
        'Réduction de 20% sur votre prochain achat de billet.',
        'discount',
        'percent',
        20.00,
        '-20%',
        '#FF6B6B',
        'fa-percent',
        0.15,  -- 15% de chance
        30,
        2
    ),
    (
        'DISCOUNT_10',
        'Réduction -10%',
        'Réduction de 10% sur votre prochain achat de billet.',
        'discount',
        'percent',
        10.00,
        '-10%',
        '#50C878',
        'fa-percent',
        0.30,  -- 30% de chance
        30,
        3
    ),
    
    -- Réductions en montant fixe
    (
        'DISCOUNT_10000',
        'Bon de 10 000 MGA',
        'Crédit de 10 000 MGA à utiliser sur votre prochain achat.',
        'discount',
        'fixed',
        10000.00,
        '10 000 MGA',
        '#FFD700',
        'fa-money-bill-wave',
        0.12,  -- 12% de chance
        60,
        4
    ),
    (
        'DISCOUNT_5000',
        'Bon de 5 000 MGA',
        'Crédit de 5 000 MGA à utiliser sur votre prochain achat.',
        'discount',
        'fixed',
        5000.00,
        '5 000 MGA',
        '#2ED573',
        'fa-money-bill-wave',
        0.20,  -- 20% de chance
        60,
        5
    ),
    
    -- Billet gratuit (très rare)
    (
        'FREE_TICKET',
        'Billet Gratuit !',
        'Gagnez un billet Standard gratuit pour l''événement de votre choix (sous conditions).',
        'free_ticket',
        'quantity',
        1.00,
        'BILLET GRATUIT',
        '#4A90E2',
        'fa-ticket-alt',
        0.02,  -- 2% de chance (très rare)
        60,
        6
    ),
    
    -- Upgrade de billet
    (
        'UPGRADE_VIP',
        'Upgrade VIP',
        'Passez en catégorie VIP sur votre prochain achat (différence offerte).',
        'upgrade',
        'quantity',
        1.00,
        'UPGRADE VIP',
        '#9B59B6',
        'fa-arrow-up',
        0.03,  -- 3% de chance (rare)
        30,
        7
    ),
    
    -- Tirage supplémentaire
    (
        'EXTRA_PLAY',
        'Rejouez !',
        'Tentez votre chance une fois de plus gratuitement !',
        'extra_play',
        'quantity',
        1.00,
        'REJOUEZ',
        '#E056FD',
        'fa-redo',
        0.15,  -- 15% de chance
        7,
        8
    )
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    probability = EXCLUDED.probability,
    color = EXCLUDED.color,
    updated_at = now();

-- ============================================================
-- MODIFIER LA TABLE ticket_chance_entries POUR RÉFÉRENCER LES PRIX
-- ============================================================

-- Ajouter la colonne prize_id si elle n'existe pas
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'aiolia' 
        AND table_name = 'ticket_chance_entries' 
        AND column_name = 'prize_id'
    ) THEN
        ALTER TABLE aiolia.ticket_chance_entries 
        ADD COLUMN prize_id BIGINT REFERENCES aiolia.ticket_chance_prizes(id);
        
        -- Index pour les jointures
        CREATE INDEX IF NOT EXISTS idx_ticket_chance_entries_prize 
            ON aiolia.ticket_chance_entries(prize_id);
    END IF;
END
$$;

-- ============================================================
-- VUE POUR RÉCUPÉRER LES PRIX ACTIFS AVEC LEURS PROBABILITÉS
-- ============================================================

CREATE OR REPLACE VIEW aiolia.v_active_prizes AS
SELECT 
    id,
    code,
    name,
    description,
    category,
    value_type,
    value,
    display_label,
    color,
    icon,
    probability,
    validity_days,
    min_order_amount,
    applicable_categories,
    applicable_event_ids
FROM aiolia.ticket_chance_prizes
WHERE is_active = TRUE
ORDER BY display_order;

-- Vérifier que les probabilités totalisent 100%
SELECT 
    SUM(probability) as total_probability,
    CASE 
        WHEN SUM(probability) = 1.0 THEN '✓ Probabilités correctes (100%)'
        ELSE '⚠ Attention: probabilités = ' || (SUM(probability) * 100)::TEXT || '%'
    END as status
FROM aiolia.ticket_chance_prizes
WHERE is_active = TRUE;

